//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EldenRingTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EldenRingTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 a1 00 00 00 00 00    movabs rax,ds:0x0
        ///00 00 00
        ///48 8b 80 08 e5 01 00    mov    rax,QWORD PTR [rax+0x1e508]
        ///48 3b 46 08             cmp    rax,QWORD PTR [rsi+0x8]
        ///75 0a                   jne    22 &lt;normal&gt;
        ///58                      pop    rax
        ///48 83 fe 00             cmp    rsi,0x0
        ///e9 00 00 00 00          jmp    22 &lt;normal&gt;
        ///000000000022 &lt;normal&gt;:
        ///58                      pop    rax
        ///80 bf 5f 02 00 00 00    cmp    BYTE PTR [rdi+0x25f],0x0
        ///e9 00 00 00 00          jm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfinitePoise {
            get {
                return ResourceManager.GetString("InfinitePoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///52                      push   rdx
        ///41 50                   push   r8
        ///41 51                   push   r9
        ///48 83 ec 70             sub    rsp,0x70
        ///0f 11 04 24             movups XMMWORD PTR [rsp],xmm0
        ///0f 11 4c 24 10          movups XMMWORD PTR [rsp+0x10],xmm1
        ///0f 11 54 24 20          movups XMMWORD PTR [rsp+0x20],xmm2
        ///0f 11 5c 24 30          movups XMMWORD PTR [rsp+0x30],xmm3
        ///0f 11 64 24 40          movups XMMWORD PTR [rsp+0x40],xmm4
        ///0f 11 6c 24 50          movups XMM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReducedTargetView {
            get {
                return ResourceManager.GetString("ReducedTargetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8b 49 08             mov    rcx,QWORD PTR [rcx+0x8]
        ///81 fa a5 2e 00 00       cmp    edx,0x2ea5
        ///75 03                   jne    f &lt;normal&gt;
        ///48 31 c9                xor    rcx,rcx
        ///00000000000f &lt;normal&gt;:
        ///48 85 c9                test   rcx,rcx
        ///e9 00 00 00 00          jmp    17 &lt;normal+0x8&gt;.
        /// </summary>
        internal static string RykardNoMega {
            get {
                return ResourceManager.GetString("RykardNoMega", resourceCulture);
            }
        }
    }
}
